Style/AndOr:
  EnforcedStyle: conditionals
Style/CaseIndentation:
  IndentOneStep: true
Style/NumericLiterals:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": "[]"
    "%W": "[]"
    "%i": "[]"
    "%I": "[]"
    "%r": "()"
Style/SignalException:
  EnforcedStyle: semantic
Style/SingleLineBlockParams:
  Enabled: false
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Metrics/LineLength:
  Max: 120
AllCops:
  TargetRubyVersion: 2.3
